Repository CirrusRedOrg/EntityFrameworkCore.Jet, pull requests merged in 2020-11, with the labels that each got.

#63 Change default data access library to ODBC and improve file extension handling
  src/System.Data.Jet/JetConfiguration.cs
  src/System.Data.Jet/JetConnection.cs
  src/System.Data.Jet/JetStoreSchemaDefinition/JetStoreDatabaseHandling.cs
Labels: enhancement

#64 Fix translation of parameterless Trim(), TrimStart() and TrimEnd() methods
  src/EFCore.Jet/Query/ExpressionTranslators/Internal/JetStringMethodTranslator.cs
Labels: bug, enhancement

#68 Improve project and CI
  Dependencies.targets
  Directory.Build.props
  Directory.Build.targets
  EntityFrameworkCore.Jet.sln
  Version.targets
  azure-pipelines.yml
  build/dependencies.props
  global.json
  src/Directory.Build.props
  src/EFCore.Jet/EFCore.Jet.csproj
  src/EFCore.Jet/Extensions/JetDbContextOptionsBuilderExtensions.cs
  src/EFCore.Jet/Infrastructure/JetDbContextOptionsBuilder.cs
  src/System.Data.Jet/System.Data.Jet.csproj
  test/Directory.Build.props
  test/EFCore.Jet.FunctionalTests/EFCore.Jet.FunctionalTests.csproj
  test/EFCore.Jet.FunctionalTests/JetMigrationSqlGeneratorTest.cs
  test/EFCore.Jet.FunctionalTests/Scaffolding/JetDatabaseModelFactoryTest.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/TestEnvironment.cs
  test/EFCore.Jet.IntegrationTests/EFCore.Jet.IntegrationTests.csproj
  test/EFCore.Jet.Tests/EFCore.Jet.Tests.csproj
  test/JetProviderExceptionTests/JetProviderExceptionTests.csproj
  test/System.Data.Jet.Test/System.Data.Jet.Test.csproj
Labels: enhancement

#70 Use new information schema syntax for HistoryRepository checks
  src/EFCore.Jet/Migrations/Internal/JetHistoryRepository.cs
  src/EFCore.Jet/Properties/JetStrings.Designer.cs
  src/EFCore.Jet/Properties/JetStrings.resx
Labels: bug

#67 Add setting to use default value if column has an unexpected null value
  src/System.Data.Jet/JetConfiguration.cs
  src/System.Data.Jet/JetDataReader.cs
Labels: enhancement

#72 Fix connection string conversion from ODBC to OLE DB
  src/System.Data.Jet/AdoxSchema.cs
  src/System.Data.Jet/DaoSchema.cs
  src/System.Data.Jet/DbConnectionStringBuilderExtensions.cs
Labels: bug

#74 Add ODBC and OLE DB specific packages
  Directory.Build.props
  EFCore.Jet.sln
  src/Directory.Build.props
  src/EFCore.Jet.Odbc/EFCore.Jet.Odbc.csproj
  src/EFCore.Jet.Odbc/Extensions/JetOdbcDbContextOptionsBuilderExtensions.cs
  src/EFCore.Jet.OleDb/EFCore.Jet.OleDb.csproj
  src/EFCore.Jet.OleDb/Extensions/JetDbContextOptionsBuilderExtensions.cs
  src/EFCore.Jet/EFCore.Jet.csproj
  src/EFCore.Jet/Extensions/JetDbContextOptionsBuilderExtensions.cs
  src/System.Data.Jet/JetFactory.cs
Labels: enhancement

#77 Trim called without arguments throws index out of range
  src/EFCore.Jet/Query/ExpressionTranslators/Internal/JetStringMethodTranslator.cs
  test/EFCore.Jet.FunctionalTests/Query/SimpleQueryJetTest.Functions.cs
Labels: bug
