Repository CirrusRedOrg/EntityFrameworkCore.Jet, pull requests merged in 2020-12, with the labels that each got.

#82 Fix data and test infrastructure and scaffolding
  .gitignore
  Development.props
  Directory.Build.props
  src/EFCore.Jet.Data/JetDataReader.cs
  src/EFCore.Jet.Odbc/EFCore.Jet.Odbc.csproj
  src/EFCore.Jet.OleDb/EFCore.Jet.OleDb.csproj
  src/EFCore.Jet/Scaffolding/Internal/JetDatabaseModelFactory.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/JetDatabaseCleaner.cs
  test/EFCore.Jet.Tests/EFCore.Jet.Tests.csproj
Labels: internal

#81 Fix DEFAULT clause for HasDefaultValueSql()
  azure-pipelines.yml
  src/EFCore.Jet/Migrations/JetMigrationsSqlGenerator.cs
  test/EFCore.Jet.FunctionalTests/JetMigrationSqlGeneratorTest.cs
  test/EFCore.Jet.Tests/JetMigrationTest.cs
Labels: bug

#84 Fix runtime checks for appropriate data access library version
  src/EFCore.Jet.Data/JetFactory.cs
Labels: bug

#85 Fix DateTime expressions for HasDefaultValue() and add support for fractions of a second
  azure-pipelines.yml
  src/EFCore.Jet.Data/JetDataReader.cs
  src/EFCore.Jet/Migrations/JetMigrationsSqlGenerator.cs
  src/EFCore.Jet/Query/Internal/JetDateTimeExpressionVisitor.cs
  src/EFCore.Jet/Query/Internal/JetQueryTranslationPostprocessor.cs
  src/EFCore.Jet/Storage/Internal/JetDateTimeOffsetTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetDateTimeTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetTimeSpanTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetTypeMappingSource.cs
  src/Shared/SharedTypeExtensions.cs
  test/EFCore.Jet.FunctionalTests/JetMigrationSqlGeneratorTest.cs
  test/EFCore.Jet.FunctionalTests/Query/SimpleQueryJetTest.Where.cs
  test/EFCore.Jet.FunctionalTests/Query/SimpleQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Scaffolding/JetDatabaseModelFactoryTest.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/TestEnvironment.cs
  test/EFCore.Jet.Tests/ContextBase.cs
  test/EFCore.Jet.Tests/EFCore.Jet.Tests.csproj
  test/EFCore.Jet.Tests/JetDateTimeTest.cs
  test/EFCore.Jet.Tests/JetMigrationTest.cs
  test/EFCore.Jet.Tests/TestBase.cs
  test/EFCore.Jet.Tests/config.json
Labels: enhancement

#87 Fix JetCommand regarding CREATE PROCEDURE statements and command splitting
  src/EFCore.Jet.Data/JetCommand.cs
Labels: bug

#88 Fix CREATE/DROP DATABASE related issues
  src/EFCore.Jet.Data/JetConnection.cs
  src/EFCore.Jet.Data/JetStoreSchemaDefinition/JetStoreDatabaseHandling.cs
  src/EFCore.Jet/Storage/Internal/JetDatabaseCreator.cs
  test/EFCore.Jet.Data.Tests/ConnectionStringTest.cs
  test/EFCore.Jet.Data.Tests/CreateDatabaseTest.cs
  test/EFCore.Jet.Tests/TestBase.cs
Labels: bug

#89 Fix schema and rename related issues and tests
  src/EFCore.Jet.Data/AdoxSchema.cs
  src/EFCore.Jet.Data/AdoxWrapper.cs
  src/EFCore.Jet.Data/DaoSchema.cs
  src/EFCore.Jet.Data/ISchemaOperationsProvider.cs
  src/EFCore.Jet.Data/JetCommand.cs
  src/EFCore.Jet.Data/JetStoreSchemaDefinition/JetRenameHandling.cs
  src/EFCore.Jet.Data/JetStoreSchemaDefinition/JetSchemaOperationsHandling.cs
  src/EFCore.Jet.Data/PreciseSchema.cs
  src/EFCore.Jet.Data/SchemaProvider.cs
  src/EFCore.Jet/Migrations/JetMigrationsSqlGenerator.cs
  test/EFCore.Jet.Data.Tests/AdoxTest.cs
  test/EFCore.Jet.Data.Tests/JetInformationSchemaTest.cs
  test/EFCore.Jet.Data.Tests/SchemaOperationsTest.cs
Labels: bug

#90 When creating databases, automatically use the latest database version that is supported by the current file extension
  src/EFCore.Jet.Data/AdoxDatabaseCreator.cs
  src/EFCore.Jet.Data/DaoDatabaseCreator.cs
  src/EFCore.Jet.Data/IJetDatabaseCreator.cs
  src/EFCore.Jet.Data/JetConnection.cs
  src/EFCore.Jet.Data/JetDatabaseCreator.cs
  src/EFCore.Jet.Data/PreciseDatabaseCreator.cs
  test/EFCore.Jet.Data.Tests/Helpers.cs
Labels: bug

#91 Add support for PASSWORD clause in EFCore.Jet specific CREATE DATABASE statement
  src/EFCore.Jet.Data/JetStoreSchemaDefinition/JetStoreDatabaseHandling.cs
  src/EFCore.Jet/Migrations/JetMigrationsSqlGenerator.cs
  src/EFCore.Jet/Migrations/Operations/JetCreateDatabaseOperation.cs
  src/EFCore.Jet/Storage/Internal/JetDatabaseCreator.cs
  test/EFCore.Jet.Data.Tests/CreateDatabaseTest.cs
Labels: enhancement

#92 Fix remaining EFCore.Jet.Data tests
  azure-pipelines.yml
  src/EFCore.Jet.Data/AdoxDatabaseCreator.cs
  src/EFCore.Jet.Data/AdoxSchema.cs
  src/EFCore.Jet.Data/DaoDatabaseCreator.cs
  src/EFCore.Jet.Data/DaoSchema.cs
  src/EFCore.Jet.Data/IJetDatabaseCreator.cs
  src/EFCore.Jet.Data/ISchemaOperationsProvider.cs
  src/EFCore.Jet.Data/ISchemaProvider.cs
  src/EFCore.Jet.Data/JetCommand.cs
  src/EFCore.Jet.Data/JetCommandParser.cs
  src/EFCore.Jet.Data/JetConnection.cs
  src/EFCore.Jet.Data/JetDatabaseCreator.cs
  src/EFCore.Jet.Data/PreciseDatabaseCreator.cs
  src/EFCore.Jet.Data/PreciseSchema.cs
  src/EFCore.Jet.Data/SchemaProvider.cs
  test/EFCore.Jet.Data.Tests/ConnectionPoolingTest.cs
  test/EFCore.Jet.Data.Tests/E2E.sql
  test/EFCore.Jet.Data.Tests/JetInformationSchemaTest.cs
  test/EFCore.Jet.Data.Tests/JetStoreSchemaDefinitionRetrieveTest.cs
Labels: internal

#94 Resolve IJetOptions for design time services
  src/EFCore.Jet/Design/Internal/JetDesignTimeServices.cs
Labels: bug
