Repository CirrusRedOrg/EntityFrameworkCore.Jet, pull requests merged in 2023-12, with the labels that each got.

#180 Add options to configure the manner of mapping DateTimeOffset
  src/EFCore.Jet/Infrastructure/Internal/IJetOptions.cs
  src/EFCore.Jet/Infrastructure/Internal/JetOptionsExtension.cs
  src/EFCore.Jet/Infrastructure/JetDbContextOptionsBuilder.cs
  src/EFCore.Jet/Internal/JetOptions.cs
  src/EFCore.Jet/Storage/Internal/JetDateTimeOffsetTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetTypeMappingSource.cs
Labels: enhancement

#188 Properly read and write UTC values for DateTimeOffset
  Version.props
  src/EFCore.Jet.Data/JetDataReader.cs
  src/EFCore.Jet/Storage/Internal/JetDateTimeOffsetTypeMapping.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/QueryBugsTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/JetTestHelpers.cs
Labels: bug

#194 Fix CI for releases.
  .github/workflows/push.yml
  Version.props
Labels: internal

#196 Misc test fixes
  src/EFCore.Jet.Data/JetCommand.cs
  src/EFCore.Jet/Internal/JetModelValidator.cs
  src/EFCore.Jet/Query/Sql/Internal/JetQuerySqlGenerator.cs
  src/EFCore.Jet/Update/Internal/JetUpdateSqlGenerator.cs
  test/EFCore.Jet.FunctionalTests/EntitySplittingSqlServerTest.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/JetQueryTriggersTest.cs
  test/EFCore.Jet.FunctionalTests/JetTriggersTest.cs
  test/EFCore.Jet.FunctionalTests/Query/FromSqlQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCRelationshipsQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Scaffolding/JetDatabaseModelFactoryTest.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
  test/EFCore.Jet.FunctionalTests/Update/StoredProcedureUpdateJetTest.cs
  test/EFCore.Jet.FunctionalTests/ValueConvertersEndToEndJetTest.cs
Labels: internal

#197 Ensure strings with length greater than 255 are converted to long text/memo
  src/EFCore.Jet/Storage/Internal/JetStringTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetTypeMappingSource.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/JetMigrationsSqlGeneratorTest.cs
Labels: bug

#198 Assert Translation Failed for certain primitive collection tests
  src/EFCore.Jet/Properties/JetStrings.Designer.cs
  src/EFCore.Jet/Properties/JetStrings.resx
  src/EFCore.Jet/Query/Internal/JetQueryableMethodTranslatingExpressionVisitor.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/NorthwindAggregateOperatorsQueryJetTest.ResultOperators.cs
  test/EFCore.Jet.FunctionalTests/Query/PrimitiveCollectionsQueryJetTest.cs
Labels: internal

#199 Fix up some datetimeoffset tests
  src/EFCore.Jet/Query/ExpressionTranslators/Internal/JetDateTimeMethodTranslator.cs
  src/EFCore.Jet/Storage/Internal/JetDateTimeOffsetTypeMapping.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetTest.cs
Labels: bug, internal

#200 Reintroduce the SkipTakeCollapsingExpressionVisitor
  src/EFCore.Jet.Data/JetCommand.cs
  src/EFCore.Jet/Query/Internal/JetParameterBasedSqlProcessor.cs
  src/EFCore.Jet/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/NorthwindGroupByQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/NorthwindMiscellaneousQueryJetTest.cs
Labels: bug

#201 Remove UDF function tests.
  test/EFCore.Jet.FunctionalTests/JetComplianceTest.cs
  test/EFCore.Jet.FunctionalTests/Query/UdfDbFunctionJetTests.cs
Labels: internal

#202 Fix Any,All,Contains with Many to Many relationships within a Where clause
  src/EFCore.Jet/Query/Sql/Internal/JetQuerySqlGenerator.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/ManyToManyNoTrackingQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/ManyToManyQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCManyToManyNoTrackingQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCManyToManyQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTManyToManyNoTrackingQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTManyToManyQueryJetTest.cs
Labels: bug
