Repository CirrusRedOrg/EntityFrameworkCore.Jet, pull requests merged in 2023-10, with the labels that each got.

#144 Fix and update dependencies and project files.
  .gitignore
  Dependencies.targets
  Development.props.sample
  Directory.Build.props
  EFCore.Jet.sln
  NuGet.Config
  src/EFCore.Jet.Data/EFCore.Jet.Data.csproj
  src/EFCore.Jet.Odbc/EFCore.Jet.Odbc.csproj
  src/EFCore.Jet.OleDb/EFCore.Jet.OleDb.csproj
  src/EFCore.Jet/EFCore.Jet.csproj
  test/EFCore.Jet.CustomBaseTests/EFCore.Jet.CustomBaseTests.csproj
  test/EFCore.Jet.Data.Tests/EFCore.Jet.Data.Tests.csproj
  test/EFCore.Jet.FunctionalTests/EFCore.Jet.FunctionalTests.csproj
  test/EFCore.Jet.FunctionalTests/TestUtilities/JetTestStore.cs
  test/EFCore.Jet.IntegrationTests/EFCore.Jet.IntegrationTests.csproj
  test/EFCore.Jet.Tests/EFCore.Jet.Tests.csproj
  test/JetProviderExceptionTests/JetProviderExceptionTests.csproj
  version.xml
Labels: internal

#146 Fix AZDO CI script
  azure-pipelines.yml
Labels: internal

#145 Revert pull-in of GearsOfWar related classes and remove constraint
  EFCore.Jet.sln
  src/EFCore.Jet/Extensions/JetReferenceCollectionBuilderExtensions.cs
  src/EFCore.Jet/Metadata/Internal/JetAnnotationProvider.cs
  test/EFCore.Jet.CustomBaseTests/EFCore.Jet.CustomBaseTests.csproj
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/AmmunitionType.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/City.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/CogTag.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/Faction.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/Gear.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarContext.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarData.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarFromSqlQueryTestBase.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarQueryFixtureBase.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarQueryRelationalFixture.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarQueryRelationalTestBase.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/GearsOfWarQueryTestBase.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/LocustCommander.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/LocustHighCommand.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/LocustHorde.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/LocustLeader.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/MilitaryRank.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/Mission.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/Officer.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/Squad.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/SquadMission.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/TPCGearsOfWarQueryRelationalFixture.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/TPCGearsOfWarQueryRelationalTestBase.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/TPTGearsOfWarQueryRelationalFixture.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/TPTGearsOfWarQueryRelationalTestBase.cs
  test/EFCore.Jet.CustomBaseTests/GearsOfWarModel/Weapon.cs
  test/EFCore.Jet.CustomBaseTests/Readme.md
  test/EFCore.Jet.FunctionalTests/EFCore.Jet.FunctionalTests.csproj
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarFromSqlQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetFixture.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetTest.cs
Labels: internal

#153 Add docker files for testing
  .docker/BuildAllDockerfiles.ps1
  .docker/windows-ace-12.0-x64.dockerfile
  .docker/windows-ace-12.0-x86.dockerfile
  .docker/windows-ace-16.0-x64.dockerfile
  .docker/windows-ace-16.0-x86.dockerfile
  .docker/windows-ace-none-x64.dockerfile
  .docker/windows-ace-none-x86.dockerfile
  .dockerignore
  .gitignore
  Directory.Build.props
Labels: internal

#152 Add XUnit infrastructure to handle unsupported statements and test runner crashes
  test/EFCore.Jet.FunctionalTests/EFCore.Jet.FunctionalTests.csproj
  test/EFCore.Jet.FunctionalTests/Properties/AssemblyInfo.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/Xunit/AscendingTestCaseOrderer.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/Xunit/AscendingTestCollectionOrderer.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/Xunit/ExceptionTestCaseOrderer.cs
  test/EFCore.Jet.FunctionalTests/TestUtilities/Xunit/RandomTestCaseOrderer.cs
  test/EFCore.Jet.Tests/EFCore.Jet.Tests.csproj
  test/Shared/TestUtilities/Attributes/AccessProviderTypeVariation.cs
  test/Shared/TestUtilities/Attributes/TestRunnerCrashAttribute.cs
  test/Shared/TestUtilities/Xunit/AscendingTestCaseOrderer.cs
  test/Shared/TestUtilities/Xunit/AscendingTestCollectionOrderer.cs
  test/Shared/TestUtilities/Xunit/ExceptionTestCaseOrderer.cs
  test/Shared/TestUtilities/Xunit/JetConditionalFactDiscoverer.cs
  test/Shared/TestUtilities/Xunit/JetConditionalFactTestCase.cs
  test/Shared/TestUtilities/Xunit/JetConditionalTheoryDiscoverer.cs
  test/Shared/TestUtilities/Xunit/JetConditionalTheoryTestCase.cs
  test/Shared/TestUtilities/Xunit/JetXunitTestCaseRunner.cs
  test/Shared/TestUtilities/Xunit/JetXunitTestFramework.cs
  test/Shared/TestUtilities/Xunit/JetXunitTestFrameworkDiscoverer.cs
  test/Shared/TestUtilities/Xunit/JetXunitTestRunner.cs
  test/Shared/TestUtilities/Xunit/JetXunitTheoryTestCaseRunner.cs
  test/Shared/TestUtilities/Xunit/RandomTestCaseOrderer.cs
Labels: enhancement, internal

#156 Move license from Apache-2.0 to MIT
  LICENSE
Labels: enhancement

#157 Fix automatic test skipping
  src/EFCore.Jet/Utilities/ExceptionExtensions.cs
  test/Shared/TestUtilities/Xunit/JetXunitTestRunner.cs
Labels: bug, internal

#151 Revert "Type MApping: a long gets mapped to integer in Jet"
  src/EFCore.Jet/Storage/Internal/JetTypeMappingSource.cs
Labels: enhancement, work-in-progress

#148 Move from AZDO to GitHub Actions.
  .github/CODEOWNERS
  .github/workflows/build.yml
  Version.props
  azure-pipelines.yml
  test/EFCore.Jet.FunctionalTests/Properties/AssemblyInfo.cs
  test/Shared/TestUtilities/Xunit/AscendingTestCaseOrderer.cs
  test/Shared/TestUtilities/Xunit/AscendingTestCollectionOrderer.cs
  test/xunit.runner.json
Labels: enhancement, internal

#160 Update project in regards to new organization and CI.
  Directory.Build.props
  NuGet.Config
  docs/README.md
  src/Directory.Build.props
  src/EFCore.Jet/Properties/JetStrings.resx
Labels: internal

#159 Improve support for primitive collections and Json Types
  src/EFCore.Jet/Metadata/Internal/JetAnnotationProvider.cs
  src/EFCore.Jet/Query/Sql/Internal/JetQuerySqlGenerator.cs
  src/EFCore.Jet/Storage/Internal/JetByteArrayTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetDateTimeTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetDecimalTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetJsonTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetStringTypeMapping.cs
  src/EFCore.Jet/Storage/Internal/JetTypeMappingSource.cs
  test/EFCore.Jet.FunctionalTests/JsonTypesJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/JsonQueryAdHocJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/PrimitiveCollectionsQueryJetTest.cs
Labels: enhancement

#161 Ensure that tests that passed before still pass.
  .github/workflows/build.yml
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/Ef6GroupByJetTest.cs
Labels: enhancement, internal

#165 Fix auto commit for pull requests.
  .github/workflows/autocommit.yml
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
Labels: internal

#168 Publish test results as GitHub Checks.
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
Labels: internal

#164 Add automatic crash detection to CI and repeat crashing test runs up to 3 times.
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
Labels: enhancement, internal

#169 Auto skip statements that are not supported by Jet. Track unsupported statements in log files.
  src/EFCore.Jet/Query/Internal/JetCompatibilityExpressionVisitor.cs
  src/EFCore.Jet/Query/Internal/JetParameterBasedSqlProcessor.cs
  src/EFCore.Jet/Query/Internal/JetParameterBasedSqlProcessorFactory.cs
  src/EFCore.Jet/Query/Sql/Internal/JetQuerySqlGenerator.cs
  test/Shared/TestUtilities/Xunit/JetXunitTestRunner.cs
Labels: internal

#172 Provide a valid count argument to LEFT,RIGHT,MID
  src/EFCore.Jet.Data/JetDataReader.cs
  src/EFCore.Jet/Query/ExpressionTranslators/Internal/JetStringMethodTranslator.cs
  src/EFCore.Jet/Query/Internal/JetSqlTranslatingExpressionVisitor.cs
  src/EFCore.Jet/Query/Sql/Internal/JetQuerySqlGenerator.cs
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_odbc_x86.txt
  test/EFCore.Jet.FunctionalTests/GreenTests/ace_2010_oledb_x86.txt
  test/EFCore.Jet.FunctionalTests/Query/ComplexNavigationsQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/FunkyDataQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/GearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/NorthwindFunctionsQueryJetTest.Functions.cs
  test/EFCore.Jet.FunctionalTests/Query/NorthwindMiscellaneousQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCGearsOfWarQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCManyToManyNoTrackingQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPCManyToManyQueryJetTest.cs
  test/EFCore.Jet.FunctionalTests/Query/TPTGearsOfWarQueryJetTest.cs
Labels: bug, enhancement
